volumes:
    postgres-data:
        external: true

services:
  threapy:
    build:
        context: ./threapy
        dockerfile: ./Dockerfile.dev
    ports:
        - "8080:8000"
    volumes:
        - ./threapy:/app
    environment:
      DATABASE_URL: postgresql://user-name:password@postgres/threapy
      WAIT_HOSTS: postgres:5432
      
  postgres:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=threapy
      - POSTGRES_PASSWORD=test
    ports:
      - 15432:5432
  fastapi:
    build:
      context: sample_service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./sample_service:/app


  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: ${REACT_APP_SAMPLE_SERVICE_API_HOST}
