volumes:
  postgres-data:
    external: true
  pg-admin:
    external: true

services:
  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: example
      POSTGRES_DB: therapy
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  therapy:
    build:
      context: ./therapy
      dockerfile: ./Dockerfile.dev
    environment:
      DATABASE_URL: postgresql://example:test@db/therapy
      #postgresql://example(username):test(password)@db(database/section header)/therapy(name of database)
      WAIT_HOSTS: db:5432
      PORT: 8000
      SIGNING_KEY: eyJhbGciOiJIUzI1NiJ9.ew0KICAic3ViIjogIjEyMzQ1Njc4OTAiLA0KICAibmFtZSI6ICJBbmlzaCBOYXRoIiwNCiAgImlhdCI6IDE1MTYyMzkwMjINCn0.QNFyIFL5RDI3w2ZcxWPC_lIWj-xvp_EE7CwSTE0X-w8
    ports:
      - 8000:80
    volumes:
      - ./therapy:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: 1
